# Generated by Django 5.1.1 on 2025-01-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_galleryitem_notification_order_payment_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
            ],
        ),
    ]
