# Generated by Django 5.1.1 on 2025-04-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_sellerperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerperson',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sellerperson',
            name='contact',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sellerperson',
            name='join_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
