# Generated by Django 5.1.1 on 2025-01-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField()),
                ('payment_dattime', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
            ],
        ),
    ]
