# Generated by Django 5.1.1 on 2025-01-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('feedback_description', models.TextField()),
            ],
        ),
    ]
