# Generated by Django 5.1.1 on 2025-01-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('seller_name', models.CharField(max_length=50)),
                ('offer_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
