# Generated by Django 5.1.1 on 2025-01-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='offer',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='seller',
        ),
    ]
