# Generated by Django 5.1.1 on 2025-02-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('subCategory', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
    ]
