# Generated by Django 5.1.1 on 2025-02-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
