# Generated by Django 3.2.11 on 2025-02-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
