# Generated by Django 3.2.11 on 2025-02-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_cart_category_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
