# Generated by Django 5.1.1 on 2025-02-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
