# Generated by Django 5.1.1 on 2025-02-11 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_remove_product_category_delete_cart_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.category')),
                ('sub_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.product')),
            ],
        ),
    ]
