# Generated by Django 5.1.1 on 2025-02-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_alter_product_category_alter_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id', models.PositiveIntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('RAZORPAY', 'RazorPay')], default='COD', max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.product')),
            ],
        ),
    ]
