# Generated by Django 5.1.1 on 2025-02-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
