# Generated by Django 5.1.1 on 2025-02-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_category_product_sub_category_order_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category_one',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='sub_category_one',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='sub_category_one',
        ),
    ]
