# Generated by Django 5.1.1 on 2025-02-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_category_product_sub_category_one_order_cart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
