# Generated by Django 5.0 on 2025-02-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('None', 'None'), ('COD', 'Cash on Delivery'), ('RAZORPAY', 'RazorPay')], max_length=20),
        ),
    ]
